# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(all)"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directories:
      - "services/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(frontend)"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directories:
      - "services/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(backend)"
    open-pull-requests-limit: 20
    
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
