import { Lucia } from 'lucia';
import { DrizzleSQLiteAdapter } from '@lucia-auth/adapter-drizzle';
import { GitHub } from 'arctic';

import { getDbStatus, getDb, getSchema } from '../db';
import type { BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';

// These types would ideally be more specific, generated by Drizzle or manually defined
// to match your authUserTable, authSessionTable structures.
// For now, using 'any' as a placeholder based on db/index.ts AnySchema.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AuthUserTable = any; 
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AuthSessionTable = any;

// Cached instances for lazy initialization
let luciaInstance: Lucia | null = null;
let githubAuthInstance: GitHub | null = null;

// Helper function to check if we're in test mode
function isTestMode(): boolean {
  return process.env.NODE_ENV === 'test';
}

// Helper function for conditional logging
function logInfo(message: string): void {
  if (!isTestMode()) {
    console.log(message);
  }
}

// Lazy initialization function for Lucia
function initializeLucia(): Lucia {
  const { dialect, configured, initialized } = getDbStatus();
  
  if (!configured || !initialized) {
    throw new Error('Database not configured or initialized. Ensure database is set up before using Lucia.');
  }

  if (dialect !== 'sqlite') {
    throw new Error('Only SQLite is supported for authentication.');
  }

  // Use existing database connection and schema
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = getDb() as BetterSQLite3Database<any>;
  const schema = getSchema();
  
  const authUserTable = schema.authUser as AuthUserTable;
  const authSessionTable = schema.authSession as AuthSessionTable;

  if (!authUserTable || !authSessionTable) {
    throw new Error('Authentication tables (authUser, authSession) not found in the schema.');
  }

  // Create Lucia adapter with existing database instance
  // Note: DrizzleSQLiteAdapter expects (db, sessionTable, userTable)
  const adapter = new DrizzleSQLiteAdapter(
    db,
    authSessionTable,
    authUserTable
  );
  
  logInfo('[INFO] Lucia SQLite adapter created with existing database instance');

  return new Lucia(adapter, {
    sessionCookie: {
      name: 'session', // Important to use a generic name for production
      expires: false, // session cookies have very long lifespan (2 years)
      attributes: {
        // For development: use secure: false with sameSite: 'lax' and domain: 'localhost'
        // For production: use secure: true with sameSite: 'none' for cross-origin
        secure: process.env.NODE_ENV === 'production',
        sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax',
        path: '/', // Explicitly set path to root
        // Set domain to localhost in development to allow cross-port communication
        domain: process.env.NODE_ENV === 'production' ? undefined : 'localhost',
      },
    },
    getUserAttributes: (attributes: DatabaseUserAttributes) => {
      return {
        username: attributes.username,
        email: attributes.email,
        firstName: attributes.first_name, // Ensure this matches the casing in DatabaseUserAttributes
        lastName: attributes.last_name,   // Ensure this matches the casing in DatabaseUserAttributes
        authType: attributes.auth_type,
        githubId: attributes.github_id,
      };
    },
    getSessionAttributes: () => {
      // If DatabaseSessionAttributes is empty, attributes will be {}.
      // If you add properties to DatabaseSessionAttributes, type them here.
      return {
        // any custom session attributes if needed, ensure they are in DatabaseSessionAttributes
      };
    }
  });
}

// Lazy initialization function for GitHub OAuth
async function initializeGithubAuth(): Promise<GitHub> {
  // Import GlobalSettingsInitService to get GitHub OAuth configuration
  const { GlobalSettingsInitService } = await import('../global-settings');
  const githubConfig = await GlobalSettingsInitService.getGitHubOAuthConfiguration();
  
  if (!githubConfig) {
    // Return a dummy GitHub instance if not configured
    // This prevents errors but the actual OAuth routes will handle the validation
    return new GitHub(
      'not_configured',
      'not_configured',
      'http://localhost:3000/api/auth/github/callback'
    );
  }
  
  return new GitHub(
    githubConfig.clientId,
    githubConfig.clientSecret,
    githubConfig.callbackUrl
  );
}

// Getter function for Lucia instance
export function getLucia(): Lucia {
  if (!luciaInstance) {
    luciaInstance = initializeLucia();
  }
  return luciaInstance;
}

// Function to reset Lucia instance (useful for testing or config changes)
export function resetLucia(): void {
  luciaInstance = null;
}

// Function to reset GitHub instance (useful for testing or config changes)
export function resetGithubAuth(): void {
  githubAuthInstance = null;
}

// Force reset on module reload in development
if (process.env.NODE_ENV !== 'production') {
  resetLucia();
}

// Force reset immediately to pick up schema changes
resetLucia();

// Getter function for GitHub OAuth instance
export async function getGithubAuth(): Promise<GitHub> {
  if (!githubAuthInstance) {
    githubAuthInstance = await initializeGithubAuth();
  }
  return githubAuthInstance;
}

// Legacy exports for backward compatibility (deprecated)
export const lucia = getLucia;
// Note: githubAuth is now async, so legacy usage may need updating
export const githubAuth = getGithubAuth;

// IMPORTANT: Define DatabaseUserAttributes and DatabaseSessionAttributes
// These interfaces are crucial for type safety with Lucia.
// You should define them based on the columns in your authUser and authSession tables.

// Corresponds to the columns in your `authUser` table that you want Lucia to handle.
interface DatabaseUserAttributes {
  username: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  auth_type: 'email_signup' | 'github';
  github_id: string | null;
}

// Corresponds to any custom columns in your `authSession` table.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface DatabaseSessionAttributes {
  // exampleProperty?: string; // Add any custom session attributes here
}

declare module 'lucia' {
  interface Register {
    Lucia: typeof lucia;
    DatabaseUserAttributes: DatabaseUserAttributes;
    DatabaseSessionAttributes: DatabaseSessionAttributes;
  }
}

// Ensure you have GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET in your .env file
// For example:
// GITHUB_CLIENT_ID=your_client_id
// GITHUB_CLIENT_SECRET=your_client_secret
