openapi: 3.0.0
info:
  title: DeployStack Backend API
  description: API documentation for DeployStack Backend
  version: 0.20.5
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth_session
  schemas: {}
paths:
  /:
    get:
      responses:
        "200":
          description: Default Response
  /api/users-example:
    get:
      responses:
        "200":
          description: Default Response
  /api/db/status:
    get:
      responses:
        "200":
          description: Default Response
  /api/db/setup:
    post:
      responses:
        "200":
          description: Default Response
  /register:
    post:
      responses:
        "200":
          description: Default Response
  /login:
    post:
      responses:
        "200":
          description: Default Response
  /logout:
    post:
      summary: User logout
      tags:
        - Authentication
      description: Invalidates the current user session and clears authentication
        cookies. This endpoint can be called even without an active session.
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the logout operation was successful
                  message:
                    type: string
                    description: Human-readable message about the logout result
                required:
                  - success
                  - message
              examples:
                example1:
                  value:
                    success: true
                    message: Logged out successfully.
                example2:
                  value:
                    success: true
                    message: No active session to logout or already logged out.
  /api/roles:
    get:
      responses:
        "200":
          description: Default Response
    post:
      responses:
        "200":
          description: Default Response
  /api/roles/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
    put:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
  /api/roles/permissions:
    get:
      responses:
        "200":
          description: Default Response
  /api/users:
    get:
      responses:
        "200":
          description: Default Response
  /api/users/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
    put:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
  /api/users/{id}/role:
    put:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
  /api/users/stats:
    get:
      responses:
        "200":
          description: Default Response
  /api/users/role/{roleId}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: roleId
          required: true
      responses:
        "200":
          description: Default Response
  /api/users/me:
    get:
      responses:
        "200":
          description: Default Response
  /api/users/me/teams:
    get:
      responses:
        "200":
          description: Default Response
  /api/settings/groups:
    get:
      responses:
        "200":
          description: Default Response
  /api/settings:
    get:
      responses:
        "200":
          description: Default Response
    post:
      responses:
        "200":
          description: Default Response
  /api/settings/{key}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: key
          required: true
      responses:
        "200":
          description: Default Response
    put:
      parameters:
        - schema:
            type: string
          in: path
          name: key
          required: true
      responses:
        "200":
          description: Default Response
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: key
          required: true
      responses:
        "200":
          description: Default Response
  /api/settings/group/{groupId}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: groupId
          required: true
      responses:
        "200":
          description: Default Response
  /api/settings/categories:
    get:
      responses:
        "200":
          description: Default Response
  /api/settings/search:
    post:
      responses:
        "200":
          description: Default Response
  /api/settings/bulk:
    post:
      responses:
        "200":
          description: Default Response
  /api/settings/health:
    get:
      responses:
        "200":
          description: Default Response
  /api/auth/email/register:
    post:
      responses:
        "200":
          description: Default Response
  /api/auth/email/login:
    post:
      responses:
        "200":
          description: Default Response
  /api/auth/github/login:
    get:
      responses:
        "200":
          description: Default Response
  /api/auth/github/callback:
    get:
      responses:
        "200":
          description: Default Response
  /api/auth/logout:
    post:
      summary: User logout
      tags:
        - Authentication
      description: Invalidates the current user session and clears authentication
        cookies. This endpoint can be called even without an active session.
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the logout operation was successful
                  message:
                    type: string
                    description: Human-readable message about the logout result
                required:
                  - success
                  - message
              examples:
                example1:
                  value:
                    success: true
                    message: Logged out successfully.
                example2:
                  value:
                    success: true
                    message: No active session to logout or already logged out.
servers:
  - url: http://localhost:3000
    description: Development server
